services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      # These will be overridden by your Railway environment variables
      NODE_ENV: development
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "1337:1337"
    restart: unless-stopped
    command: npm run develop

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      API_URL: http://localhost:1337
      GRAPHQL_URL: http://localhost:1337/graphql
      NODE_ENV: development
      HOST: 0.0.0.0
    restart: unless-stopped
    command: npm run dev:docker